apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local-cluster-tooling
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster Tooling
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-tooling
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: local-cluster-tooling
  source:
    repoURL: https://github.com/cloudnativeentrepreneur/cluster-tooling.git
    targetRevision: HEAD
    path: helm
    helm:
      version: v3
      values: |
        argocd:
          project: local-cluster-tooling
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true